#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BASE_CONFIG="$REPO_DIR/codex/config.base.toml"
LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/codex/config.local.toml"
TARGET_CONFIG="$HOME/.codex/config.toml"
INSTRUCTIONS_DIR="$HOME/.codex/instructions"

mkdir -p "$(dirname "$TARGET_CONFIG")"

cat >"$TARGET_CONFIG" <<EOF
# Generated by ai-config/scripts/render-codex-config.sh
# Edit $BASE_CONFIG and $LOCAL_CONFIG instead of this file.
$(
  cat "$BASE_CONFIG"
)

profile = "concise"

[profiles.concise]
model_verbosity = "low"
model_instructions_file = "$INSTRUCTIONS_DIR/concise.md"

[profiles.technical]
model_verbosity = "high"
model_instructions_file = "$INSTRUCTIONS_DIR/technical.md"

[profiles.review]
model_verbosity = "medium"
model_instructions_file = "$INSTRUCTIONS_DIR/review.md"
EOF

if [ -f "$LOCAL_CONFIG" ]; then
  printf '\n# Local overlay\n' >>"$TARGET_CONFIG"
  cat "$LOCAL_CONFIG" >>"$TARGET_CONFIG"
fi

echo "Rendered $TARGET_CONFIG"
